### ISSUE TITLE
problem dropping files in arch linux

### ISSUE THREAD

**Issue by Virgilio-AI** [mwh/dragon#41]
so I have no problem in draggin files out from my terminal into an other app, the problem is when I try to drop using
` dragon --target --and-exit`
because it just prints the name of the files but does nothing
I am currently in arch linux and I have tried compiling it from source, also tried using bouth of the packages in the AUR but I still have the same problem. any guesses?

**Comment by mwh** [comment]
At first I read "but does nothing" as meaning it didn't exit - is that correct? It is meant to exit afterwards, but printing the filenames (URLs) is correct. What behaviour are you expecting? 

The intended behaviour of `dragon --target --and-exit` is that it should wait for a single drop, and when one comes it should print out all the entries as URLs, then terminate. If you're not seeing that, what does happen? If you are and you don't want that, what did you intend?

**Comment by canjbfeeltheesemuffins** [comment]
average IQ of arch user
