### ISSUE TITLE
Tag commit as release

### ISSUE THREAD

**Issue by TeddyDD** [mwh/dragon#6]
Hi, I'd like to package dragon for [Void Linux](https://www.voidlinux.eu/) since dragon is pretty useful in conjuction with terminal file manager I use
Void requires some version number for packaging. I'd be very grateful if you could create tag for lastest commit  (v1 or something like that). 

You can do this with
```
git tag v1
git push --tags
```

Cheers :)

**Comment by TeddyDD** [comment]
Thanks you very much :)

**Comment by TeddyDD** [comment]
@mwh have you pushed tags? I can't see any here https://github.com/mwh/dragon/tags

**Comment by mwh** [comment]
Indeed! Better now.

**Comment by TeddyDD** [comment]
Thanks :green_heart:
