### ISSUE TITLE
Dragged files not accepted by Discord

### ISSUE THREAD

**Issue by FichteFoll** [mwh/dragon#9]
For some reason, Discord doesn't accept files dragged from dragon. However, it does accept file from Nautilus and Nautilus (and FireFox) also accepts files from dragon. Any clues as to what might be going on? Is Discord at fault?

To be clear, when dragging to a Discord client, the normal on-hover popup displays but when you release the mouse button, the popup just disappears and nothing happens. Not even an error message in the console.

**Comment by mwh** [comment]
Is this the standalone Discord application? I imagine that's Chromium inside - does it work in the browser itself for you?

My guess would be that dragon is leaving something out that Discord wants to see, but I don't know what that would be.

**Comment by FichteFoll** [comment]
Yes, it's an electron application.

**Comment by FichteFoll** [comment]
I did some research on this and it appears that discord requres the move drag action according to [this comment on a trello card](https://trello.com/c/Mpo9nOzO/18-drag-and-drop-doesnt-work-on-kde-plasma#comment-5b9044ee02a8d565774d2327).

I don't exactly want to blindly add the flag to the `gtk_drag_source_set` call without studying some source code in how they handle things. Unfortunately, nautilus [doesn't seem to use that function *at all*](https://gitlab.gnome.org/search?utf8=%E2%9C%93&snippets=&scope=&repository_ref=master&search=gtk_drag_source&project_id=1) in its code base and only has `gtk_drag_dest*` calls. It may or may not be rewuired that code is added to support moving files, which includes the questions whether we should just remove the buttons or move/delete the actual file(s) as well. Maybe add a flag for the latter?

**Comment by FichteFoll** [comment]
Did some more research. This was kind of a jungle as I couldn't find a site with all the information clearly laid out. Guess the [gtk][] and [gdk][] docs ended up being the most useful.

[gtk]: https://developer.gnome.org/gtk3/stable/gtk3-Selections.html
[gdk]: https://developer.gnome.org/gdk3/stable/gdk3-Drag-and-Drop.html

Anyway, apparently drag & drop roughly operates as follows:

1. The source specifies the mime targets it supports as well as the supported actions for each. (In our case, those should be `text/plain` and `text/uri-list` and both with the same actions; currently without MOVE and ASK.)
1. Source receives `drag-begin` signal to potentially set a cursor icon or something.
1. Dest receives `drag-motion` event where it can request the targets (types) provided by the source and may optionally request the drag data to determine whether it supports these. It may then select the desired action (by calling `gdk_drop_status`), for example based on a modifier key being held, and update the cursor icon.
1. User releases mouse. Dest receives `drag-drop` signal and requests drag data from the source (again). And uses `gdk_drop_finish` to signal success of the operation.
1. Source receives `drag-data-get` and sends the requested drag data based on the selected target type.
1. Dest receives `drag-data-receive` and handles the event. It then calls
1. If the action was MOVE, source receives `drag-data-delete` which **suggests** to delete the source.
1. Source receives `drag-end` and may clean up stuff from `drag-begin`. It may also detect the chosen target and action by the dest at this point.

Experimenting with all symbols implemented and a couple debug prints, this lead to the following discoveries:

1. Discord does indeed choose the MOVE action when it certainly shouldn't, because it's not moving the file(s). It doesn't send the `drag-data-delete` signal either. Finally, if we don't specify MOVE as supported, it requests the action … 0, which is DEFAULT (and shouldn't be used according to the docs).
1. Nautilus chooses LINK, ASK, MOVE and COPY based on modifiers pressed. However, when MOVE is selected, it deletes the source files by itself and does not send `drag-data-delete`.
1. When holding Alt in Nautilus to get ASK, the selected action in `drag-end` is ASK after the popup is closed, regardless of the action chosen. No signal is received afterwards but the action is carried out as specified.
1. Chromium requests COPY, as it should.

And finally to the following questions regarding the implementation of MOVE:

1. Should dragon allow it at all? If only discord is misbehaving, I can run a locally patched version (and hope discord eventually fixes this issue that has apparently existed for years now).
1. If it was allowed, should dragon remove its buttons, the source file(s) or both when MOVE was selected?
1. Should the allowed actions be behind some flag/param? I'd rather keep the CLI simple and with sane defaults.
1. Should dragon only remove upon receiving the `drag-data-delete` signal or when detecting manually that the chosen action was MOVE and the drag was successful (using `gdk_drag_drop_succeeded` and `gdk_drag_context_get_selected_action`)?

Feedback greatly appreciated. I also made a couple fixes and debug additions in the process that I'll PR later.

**Comment by mwh** [comment]
Querying the filesystem to see if files are still present seems overcomplicated (unless it's a protocol requirement). If a second drag doesn't work because something misbehaved, or a button disappears for the same reason, so be it.

My only concern really is a file being unexpectedly moved or deleted as a result of dragging it out. I suppose in the limit that can always happen, because the recipient is given the file path, but as long as normal use won't make it happen I don't see a real problem. If that makes `--move` unnecessary, that's fine. I'm just imagining a file manager's usual behaviour as moving within filesystems unless you specifically ask to copy.

**Comment by FichteFoll** [comment]
>I'm just imagining a file manager's usual behaviour as moving within filesystems unless you specifically ask to copy.

I'd love to do some kind of field study for this, but I would imagine that file managers implement changing the cursor based on modifier keys held to clarify what the action is going to be.

To make dragon itself behave better with this convention, I will try adding that functionality for its target button. For the time being, I'll wrap up a PR with my changes so far **without allowing MOVE**, that should be safe to merge.

**Comment by echristopherson** [comment]
>     6\. Dest receives `drag-data-receive` and handles the event. It then calls

@FichteFoll, would you be able to fill in the missing word at the end of that? I can't tell from the context.

**Comment by FichteFoll** [comment]
Sorry, I don't remember what I intended to say there. I haven't toched this topic in a year and forgot to even mention that apparently discord fixed this issue on their part, because I can drag files into it without my local patches to enable the MOVE action on a different machine.

**Comment by mwh** [comment]
I'm closing this because the core issue seems to have been external and is now resolved, but there was good discussion about the modality of the program above that may be worth revisiting at some point.
